I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 85, in script call
    call test
  File "game/script.rpy", line 85, in script call
    call test
  File "game/script.rpy", line 85, in script call
    call test
  [Previous line repeated 1 more time]
ScriptError: could not find label 'test'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 85, in script call
    call test
  File "game/script.rpy", line 85, in script call
    call test
  File "D:\renpy-7.4.4-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 85, in script call
    call test
  File "game/script.rpy", line 85, in script call
    call test
  File "D:\renpy-7.4.4-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'test'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
202307 1.0
Tue Jul 11 19:22:42 2023
